# A strawpoll web application

This Spring-based application creates a strawpoll website at
`http://localhost:8080` where users can add votes to or remove then from
options, but also create entirely new options for the poll. There is also an
admin page where options can be deleted.

## How to build
[source, shell]
----
$ git clone git@github.com:chlewe/strawpoll.git
----

[start=2]
. Create a database
. Give a user all privileges to this database (create the user if necessary)
. Update the `application.properties` file located at `src/main/resources/`

[source, shell]
----
$ cd strawpoll
$ mvn clean package
----

## How to use
[source, shell]
----
$ java -jar target/strawpoll-{VERSION}.jar
----

If you are running this on a webserver, you might want to set up a reverse proxy
to port 8080.

## Admin page
The admin page is located at `/admin/` and should be secured by some kind of
authentication of the webserver. Here admins can permanently delete options of
the poll (this affects the database entries as well).

